define a = Character(name="Axolotl", color = "#FF526F", image="axolotl", who_prefix="Queen ")
define f = Character(name="Frog", color="#00C592", image="frog", who_prefix="Herzog ")
define o = Character(name="Olm", color="#9F928D", image="olm", who_prefix="Baron ")
define l = Character(name="Lungfish", color="#FF1A1A", image="lungfish", who_prefix="Don ")
define s = Character(name="Salamander", color="#E8E610", image="sal", who_prefix="Commander ")
define c = Character(name="Caecillian", color="#454397", image="cae", who_prefix="Captain ")
define t = Character(name="Toad", color="#E1C354", image="toad", who_prefix="Great ", who_suffix=" Council")
define n = Character(name="Newt", color="#FF8200", image="newt", who_prefix="Countess ")
#Peeper's text size is smaller than the normal (28), because he's a smol little thing.
define p = Character(name="Spring Peeper", image="peeper", who_prefix="Squire ", what_size=text_size.small)